base/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from . import views


urlpatterns = [
    path('',views.base,name='home'),
    path('wallet/',include('wallet.urls')),
    path('calculator/',include('calculator.urls')),
    path('converter/',include('converter.urls')),
    path('search/',include('searcher.urls')),
    path('admin/', admin.site.urls),
]

calculator/urls.py
from django.urls import path,include
from . import views
app_name = 'calculator'

urlpatterns=[
    path('',views.index,name='indexi'),
]

converter/urls.py
from django.urls import path
from . import views

app_name='converter'

urlpatterns =[
    path('bin/',views.indexbin,name='indexbin'),
    path('deci/',views.indexdeci,name='indexdeci')

]

searcher/urls.py
from django.urls import include,path
from . import views

app_name="searcher"

urlpatterns = [
    path("",views.home,name="home"),
    path("register/",views.register,name="register"),
    path("finder/",views.finder,name="finder")
]

wallet/urls.py
from django.urls import path,include
from . import views

app_name = "wallet"

urlpatterns = [
    path("about/",views.about,name="about"),
    path("login/",views.user_login,name="user_login"),
    path("logout/",views.user_logout,name="user_logout"),
    path("register/",views.register,name="register"),
    path("dashboard/",views.dashboard,name="dashboard")
]

templates/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>My First Project</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" class="active" href="http://127.0.0.1:8000/">MY First Project </a>
        </div>
        <ul class="nav navbar-nav">
          <li><a href="{% url "calculator:indexi" %}">Calculator</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="">Converter</a>
            <ul class="dropdown-menu">
              <li><a href="{% url "converter:indexbin" %}">Binary to decimal</a></li>
              <li><a href="{% url "converter:indexdeci" %}">Decimal to binary</a></li>
            </ul>
          </li>
          <li><a href="{% url "wallet:about" %}">Wallet</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="">Searcher</a>
            <ul class="dropdown-menu">
              <li><a href="{% url "searcher:home" %}">About</a></li>
              <li><a href="{% url "searcher:finder" %}">Finder</a></li>
              <li><a href="{% url "searcher:register" %}">Register</a></li>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="{% url "wallet:user_login" %}"><span class="glyphicon glyphicon-log-in"> Login</a></li> -->
        <!-- {% if user.is_authenticated %}
              <li> <a href="{% url "wallet:user_logout" %}">Logout</a></li>
        {% else %}
              <li><a href="{% url "wallet:user_login" %}"><span class="glyphicon glyphicon-log-in">Login</a></li>
        {% endif %} -->
        </ul>
      </div>
    </nav>
    {% block body_block %}
      <h1>This is the home page....</h1>
      <!-- <h1>{{base_url}}</h1> -->
    {% endblock %}

  </body>
</html>