base/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path,include
from . import views


urlpatterns = [
    path('',views.base,name='home'),
    path('wallet/',include('wallet.urls')),
    path('calculator/',include('calculator.urls')),
    path('converter/',include('converter.urls')),
    path('search/',include('searcher.urls')),
    path('admin/', admin.site.urls),
]

wallet/urls.py
from django.urls import path,include
from . import views

app_name = "wallet"

urlpatterns = [
    path("about/",views.about,name="about"),
    path("login/",views.user_login,name="user_login"),
    path("logout/",views.user_logout,name="user_logout"),
    path("register/",views.register,name="register"),
    path("dashboard/",views.dashboard,name="dashboard")
]

wallet/models.py
from django.db import models
# Create your models here.

class UserProfileInfo(models.Model):

    portfolio = models.URLField(blank=True)
    date = models.DateTimeField(auto_now_add = True,editable=True)
    joker = models.CharField(max_length=100,blank = True)
    balance = models.PositiveIntegerField()

    def finder(self,usern):
        print(self.user.username)
        if(self.user.username==usern):
            return True
        else:
            return False

    def __str__(self):
        return str(self.user)

wallet/forms.py
from django import forms
from . import models


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = models.UserProfileInfo
        fields = ('portfolio',)

class adder(forms.Form):
    value=forms.IntegerField()

wallet/views.py
from django.shortcuts import render
from . import forms
from . import models
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout


# Create your views here.
def about(request):
    return render(request,"wallet/about.html")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('wallet:about'))


def user_login(request):
    invalid_user = False
    acc_not_active = False

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request,username=username,password=password)

        if user is not None:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('wallet:dashboard'))
            else:
                acc_not_active = True
                return render(request,"wallet/login.html",{'invalid_user':invalid_user,'acc_not_active':acc_not_active})
        else:
            print("Invalid User")
            print("Username: {} and password {}".format(username,password))
            invalid_user = True
            return render(request,'wallet/login.html',{'invalid_user':invalid_user,'acc_not_active':acc_not_active})
    else:
        return render(request,"wallet/login.html",{'invalid_user':invalid_user,'acc_not_active':acc_not_active})



def register(request):
    registered = False

    if request.method == "POST":
        user_form = forms.UserForm(request.POST)
        profile_form = forms.UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user =  user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.balance = 0
            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = forms.UserForm()
        profile_form = forms.UserProfileForm()

    return render(request,"wallet/register.html",{"user_form":user_form,"profile_form":profile_form,'registered':registered})




@login_required
def dashboard(request):
    # if request.user.is_authenticated():
    userv=request.user.id
    t = models.UserProfileInfo.objects.get(user__id=userv)
    # y = models.UserProfileInfo.objects.get(user=t)
    # bal
    # print(user.is_authenticated)
    return render(request,"wallet/dashboard.html",{'user':userv})

templates/wallet/about.html
{% extends 'basic.html' %}

{% block body_block %}
  <p> We also offer you to keep track of your money, If you want to use that feature LOGIN </p>
  <p>New User Register here: <a href="{% url 'wallet:register' %}">REGISTER</a></p>
  <p>Old User Login here: <a href="{% url 'wallet:user_login' %}">LOGIN</a></p>
{% endblock %}

templates/wallet/dashboard.html
{% extends 'basic.html' %}

{% block body_block %}
  <!-- <h3>BALANCE : {{balance.date}}</h3>
  <!-- {% for x in balance %}
    <p>{{x.user.username}}</p>
  {% endfor %} -->
  <!-- <h3>hello</h3> -->
  <!-- <p></p><p></p><p></p>
  <form method="post">
    {%csrf_token%}
    <p>Deposit Money : {{adder.as_p}}<input type="submit" name="deposit" value="Deposit"></p>
    <p>Deposit Money : {{adder.as_p}}<input type="submit" name="withdraw" value="Withdrwa"></p>
  </form>-->
  <h1>h{{user}}</h1>
  {% for x in uservi %}
      {{x}}<p>f</p>
  {% endfor %}
{% endblock %}

templates/wallet/login.html
{% extends 'basic.html' %}

{% block body_block %}
  <div class="jumbotron">
    <h1>Please Login</h1>
    <form  action="{% url 'wallet:user_login' %}" method="post">
      {% csrf_token %}
      <p><label for="username">Username:</label><input type="text" name="username" placeholder="Enter User Name"></p>

      <p><label for="password">Password:</label>
      <input type="password" name="password" ></p>
      <input type="submit" name="" value="Login">
      {% if invalid_user %}
        <p>***INVALID DETAILS***</p>
      {% endif %}
      {% if acc_not_active %}
        <p>***Account Not Active***</p>
      {% endif %}
    </form>
  </div>
{% endblock %}

templates/wallet/register.html
{% extends 'basic.html' %}

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registering</h1>
    {% else %}
        <h1>Register Here!!!</h1>
        <h3>Just Fill out The form</h3>
        <form method="post">
          {% csrf_token %}
          {{ user_form.as_p}}
          {{ profile_form.as_p }}
          <input type="submit" value="register">
        </form>

    {% endif %}
  </div>

{% endblock %}